# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Anasayfa"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Firma Bilgileri"
  pageref = "firma-bilgileri"
  weight = 20

[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 30

[[main]]
  name = "WhatsApp"
  url = "https://api.whatsapp.com/send?phone=905057286950"
  weight = 40

#[[main]]
#  name = "Examples"
#  weight = 20
#[[main]]
#  name = "Recipes"
#  parent = "Examples"
#  pageRef = "guides"
#  weight = 10
#[[main]]
#  name = "Samples"
#  parent = "Examples"
#  pageRef = "samples"
#  weight = 20
#[[main]]
#  name = "Showcase"
#  parent = "Examples"
#  pageRef = "examples"
#  weight = 30

#[[main]]
#  name = "Users"
#  pageRef = "users"
#  weight = 40

#[[main]]
#  name = "Merch"
#  url = "http://tee.pub/lic/qwSlWVBL5zc"
#  weight = 50

#[[main]]
#  name = "Test"
#  pageRef = "pagTest"
#  weight = 1000

#[[main]]
#  identifier = "twitter"
#  pre = "twitter"
#  url = "https://twitter.com/burufugu"
#  weight = 60

#[[main]]
#  identifier = "mastodon"
#  pre = "mastodon"
#  url = "https://masto.ai/@blowfish"
#  weight = 70

#[[main]]
#  identifier = "github"
#  pre = "github"
#  url = "https://github.com/nunocoracao/blowfish"
#  weight = 80


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

 [[footer]]
   name = "Silivri/Ä°stanbul"
   pageRef = "/"
   weight = 10
